### PR TITLE
WSM ID: #11526

### PR DESCRIPTION
**Pull request by janleemans**
# WMS ID = 11526

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by rahul-tasker — CHANGES_REQUESTED** [review]
Binary files, like zip files are not permitted in github per Oracle's guidelines. If your zip needs to be included, please let us know and we can make a PAR link for the zip file.

**Comment by janleemans** [comment]
Can you please upload the zipfile located at https://github.com/janleemans/goldengate/blob/main/goldengate-microservices21c/prepare-setup/stack/ll-orm-mkplc-freetier.zip and share the public link so I can include it in the tutorial ?
Thanks !

**Comment by rahul-tasker** [comment]
Hi Jan, I sent you the PAR on slack

**Comment by janleemans** [comment]
Hello, ZIP file removed and in tutorial replaced by link to PAR provided.

**Review by rahul-tasker — APPROVED** [review]

**Pull request merged**
