### PR TITLE
11103-Oracle GoldenGate Microservices for Big Data 

### PR DESCRIPTION
**Pull request by smadhukumar**
Add auto startup process and Image is working as expected on Livelab tenancy

### CODE REVIEW

**Comment by smadhukumar** [comment]
Livelab team has to pull the new update to clear the conflicts

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! You need to solve the merge conflicts on your end. You can refer to the [Troubleshooting -> Issue 3: GitHub Merge Conflicts](https://oracle.github.io/learning-library/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips). Thanks!

**Review by smadhukumar — COMMENTED** [review]
Reviewed

**Comment by klazarz** [comment]
@smadhukumar can you please have a look at the conflicts? Please have a look at URLs in all index.html and manifest.json files

index.html:
https://oracle.github.io/learning-library/common/ should be https://oracle-livelabs.github.io/common/
bit.ly/golivelabs should be developer.oracle.com/livelabs

manifest.json:
https://raw.githubusercontent.com/oracle/learning-library/master/common/ should be https://oracle-livelabs.github.io/common/

Furthermore, please check that you have the correct email address entered in all of the  manfest.json files (livelabs-help-license_us@oracle.com)

**Comment by smadhukumar** [comment]
@klazarz [klazarz](https://github.com/klazarz): It has been taken care. Thank you

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved

ggma-for-bigdata/appendix/appendix.md
ggma-for-bigdata/initial-setup/initial-setup.md
ggma-for-bigdata/workshops/desktop/index.html
ggma-for-bigdata/workshops/desktop/manifest.json
ggma-for-bigdata/workshops/freetier-cloud/index.html
ggma-for-bigdata/workshops/freetier-cloud/manifest.json
ggma-for-bigdata/workshops/freetier/index.html
ggma-for-bigdata/workshops/freetier/manifest.json
ggma-for-bigdata/workshops/livelabs-cloud/index.html
ggma-for-bigdata/workshops/livelabs-cloud/manifest.json
ggma-for-bigdata/workshops/livelabs/index.html
ggma-for-bigdata/workshops/livelabs/manifest.json
ggma-for-bigdata/workshops/sandbox/index.html
ggma-for-bigdata/workshops/sandbox/manifest.json
ggma-for-bigdata/workshops/tenancy/index.html
ggma-for-bigdata/workshops/tenancy/manifest.json

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
