### PR TITLE
update redwood images + qa report + revisions

### PR DESCRIPTION
**Pull request by kwardhana**
# 11041

### CODE REVIEW

**Comment by malcherm** [comment]
Please resolve the merge conflicts.

**Comment by kwardhana** [comment]
Hi @malcherm, I have resolved the merge conflict. Please let me know if there is anything else I can do on my end. Thank you!

**Comment by malcherm** [comment]
They are still showing in the PR. Do you want to just cancel the existing PR and create a new one? Or did your changes not get included when you resolved the conflicts?
________________________________
From: Katherine Wardhana ***@***.***>
Sent: Wednesday, March 1, 2023 5:00 PM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Michelle Malcher ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] update redwood images + qa report + revisions (PR #53)


Hi @malcherm<https://urldefense.com/v3/__https://github.com/malcherm__;!!ACWV5N9M2RV99hQ!N6l4OhkDRONHGqKNJpJYb7lzVZYdVXtuBm6PiaGC3QEuGAdXCHgo65Qb80hZFhRjPcn3Ep5jbTa1n5a_vQvuuLa3KW1l0qU$>, I have resolved the merge conflict. Please let me know if there is anything else I can do on my end. Thank you!

**Comment by kwardhana** [comment]
Hi @malcherm, is it showing in the PR now? Thanks!

**Review by malcherm — APPROVED** [review]

**Comment by malcherm** [comment]
All set now! Thanks!
________________________________
From: Katherine Wardhana ***@***.***>
Sent: Wednesday, March 1, 2023 5:12 PM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Michelle Malcher ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] update redwood images + qa report + revisions (PR #53)


Hi @malcherm<https://urldefense.com/v3/__https://github.com/malcherm__;!!ACWV5N9M2RV99hQ!MIP4mKz9u5-e1QRZ2UEY_j1I3NvDW-iCzrxyD-ADZhqXeLpYqKxel0bKUUlAK7rbrPyuuSwMsOA0CS104u77fQLD-6hdty8$>, is it showing in the PR now? Thanks!

**Comment by kwardhana** [comment]
Thank you so much! :D

**Pull request merged**
