### PR TITLE
WMS ID 11326 :: Transferring the work to the UA team.

### PR DESCRIPTION
**Pull request by smadhukumar**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@smadhukumar - I do not see you on the workshop team in WMS. 
- Please check with the workshop team to add you to the workshop team in WMS. 
- Also, the workshop status in Self QA, follow the steps [HERE](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=5-labs-qa-checks#Task3:SelfQA) to perform the Self QA of the workshop and update status to Self QA Complete.

**Comment by smadhukumar** [comment]
The Correct  WMS ID is 11326. 

Self QA has been completed.

**Comment by smadhukumar** [comment]
Hi @anooshapilli ,

Transferring all the work to UA team. 

Thank you

-Madhu

**Comment by anooshapilli** [comment]
Jenny Chan and Katherine are going to take ownership of this workshop.

**Pull request merged**
