### PR TITLE
GGBD workshop

### PR DESCRIPTION
**Pull request by smadhukumar**
Modified  the initial step

### CODE REVIEW

**Review by rfontcha — CHANGES_REQUESTED** [review]
@smadhukumar  - Refer to the QA guidelines and address the following issues.

- All files must be in lowercase
- All image files must be descriptive and not simply made up of numbers (e.g 01_01.png)
- All images must have an "ALT-TEXT" in the MD file
- Remove any leftover file or unused directory inherited from the template you copied and used to add your content
- Remove README.md files
- Any other requirement in the QA doc I may have missed

**Comment by smadhukumar** [comment]
QA corrections are taken care. Merging is blocked by Livelab team

**Comment by rfontcha** [comment]
@smadhukumar - Filename must be descriptive and not numbered or representative of a task or step number. Please rename accordingly.

image

**Comment by rfontcha** [comment]
Also, it looks like this PR is also updating "**_oci-ggs-to-kafka_**". Confirm if this is part of the same workshop

**Comment by smadhukumar** [comment]
Folder " "oci-ggs-to-kafka" belongs to OCI OGG replication to Kafka which completely different workshop. I have moved files and created a new PR request "11103-Oracle GoldenGate Microservices for Big Data #9"

**Pull request merged**
