### PR TITLE
WMS ID: #11526

### PR DESCRIPTION
**Pull request by janleemans**
# Add here your WMS ID: 11526

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x ] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi @janleemans 

Please review the QA document and make the following updates in accordance with guidelines

- Numbering needs to be indented
- Images need to be indented under numbers
- Titles need to match between your workshop files and the workshop management system (WMS)
- The proceed to the next lab statement needs to be fixed to match the formatting in the QA doc
image

**Comment by janleemans** [comment]
Hello, I implemented the requested changes, can you recheck ?
Thanks !

**Review by ZRTalke — DISMISSED** [review]
Hi @janleemans 

Numbering still needs to be indented and your titles need to match exactly between your workshop files and the WMS

image

**Comment by janleemans** [comment]
Hello,

- I took exact titles from the ./tenancy/manifest.json and used them as titles in the workshops and in the WMS Topics description. 
- I already changed all the indentations of the numbers in the previous submission.  It now looks exactly like the example you provided and as in the sample lab on common/sample-livelabs-templates/sample-workshop.  Below a screenshot, can you be more explicit as to what you are expecting here ?
image

**Review by ramumg — APPROVED** [review]

**Pull request merged**
