### PR TITLE
Update OCI GoldenGate Livelabs

### PR DESCRIPTION
**Pull request by kwardhana**
Workshops: 2920, 11041, 4861

2920: 
- Updated screens
- Added alt text
- Replaced database registration with connections
- Renamed workshop folders to Sandbox and Tenancy

4861: 
- Updated screens
- Added alt text
- Replaced database registration with connections
- Renamed workshop folders to Sandbox and Tenancy

11041 (new lab): 
- Completed self-QA
- Tested new lab with existing Sandbox environment from Livelabs 2920

Added screenshots to ggs-common

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop in Workshop Management System. Can you ask someone listed as the workshop team to add you?
Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.
Thanks!

**Comment by kwardhana** [comment]
Hi Arabella,

Thank you for reaching out! A team member, Jenny Chan, just added me as a team member. Let me know if there is anything else you need from me!

Best,
Katherine Wardhana

From: Arabella Yao ***@***.***>
Date: Thursday, October 27, 2022 at 1:23 PM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Katherine Wardhana ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] Update OCI GoldenGate Livelabs (PR #34)

@arabellayao requested changes on this pull request.

Hi! Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop in Workshop Management System. Can you ask someone listed as the workshop team to add you?

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please make sure images’ names are descriptive instead of step numbers.
Can you also remove the .DS_Store files?
Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.

**Comment by kwardhana** [comment]
Hi Arabella,

Thank you for your suggestions! I have changed the image names, so it is now descriptive. I have pushed the changes to GitHub.

Also, I am using a Mac, so I cannot see/find or remove the .DS_Store files. How else can I remove these files?

Please let me know if there are any other revisions you have for me!

Best,
Katherine Wardhana

From: Arabella Yao ***@***.***>
Date: Thursday, October 27, 2022 at 6:12 PM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Katherine Wardhana ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] Update OCI GoldenGate Livelabs (PR #34)

@arabellayao requested changes on this pull request.

Hi! Please make sure images’ names are descriptive instead of step numbers.
Can you also remove the .DS_Store files?

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please rename those images in those folders descriptive names. Also double check that all other images have descriptive names. Screen Shot 2022-10-28 at 10 09 18 AM.
Screen Shot 2022-10-28 at 10 10 35 AM
To remove the .DS_Store files, I think you can go to terminal, go those folders, and use the "rm .DS_Store" command.
Thanks!

**Comment by kwardhana** [comment]
Hi Arabella,

I’ve renamed the images on the workshops I have pushed to GitHub and removed the .DS_Store files on terminal. Please let me know if there is anything else you need from me and I will make the changes on Monday!

Have a great Halloween weekend!

Best,
Katherine Wardhana

From: Arabella Yao ***@***.***>
Date: Friday, October 28, 2022 at 1:12 PM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Katherine Wardhana ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] Update OCI GoldenGate Livelabs (PR #34)

@arabellayao requested changes on this pull request.

Hi! Please rename those images in those folders descriptive names. Also double check that all other images have descriptive names. [Screen Shot 2022-10-28 at 10 09 18 AM] <https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48001060/198693795-bd6c7306-61f9-4923-ad76-daa4a02b3faf.png__;!!ACWV5N9M2RV99hQ!MV7CuZISRc3NxhAuH1IuU85UwUTZd2a4KHlvu6f78NIPJ8c9fPgF7meZ8OLsjbPlsc2YnJHA_pNwLDmeYMrYDUe1ysn-jjE$> .
[Screen Shot 2022-10-28 at 10 10 35 AM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48001060/198694042-fca4f4e4-a864-4628-83bb-2fe51e7049d4.png__;!!ACWV5N9M2RV99hQ!MV7CuZISRc3NxhAuH1IuU85UwUTZd2a4KHlvu6f78NIPJ8c9fPgF7meZ8OLsjbPlsc2YnJHA_pNwLDmeYMrYDUe1GxwLo8M$>
To remove the .DS_Store files, I think you can go to terminal, go those folders, and use the "rm .DS_Store" command.
Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please resolve merge conflicts on your branch. You can refer to this guide’s Troubleshooting #3 for help: https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved 
Conflicting files
oci-ggs/create/create.md

**Comment by kwardhana** [comment]
Hi Arabella,

I have fixed the merge conflict on GitHub. Please let me know if there is anything else you need from me!

Best,
Katherine

From: Arabella Yao ***@***.***>
Date: Saturday, October 29, 2022 at 2:17 AM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Katherine Wardhana ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] Update OCI GoldenGate Livelabs (PR #34)

@arabellayao requested changes on this pull request.

Hi! Please resolve merge conflicts on your branch. You can refer to this guide’s Troubleshooting #3<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/goldengate/pull/3__;!!ACWV5N9M2RV99hQ!PWYLab2lZ8MWeGvvx4Zr0mPpg3IhWFtvBFIiVtV9wXpvEivu9DGqBJNKdkQFXOtpKPPczb3-shNOX6xWqL25HUAnVQTwy3U$> for help: https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest*Appendix:TroubleshootingTips__;Iw!!ACWV5N9M2RV99hQ!PWYLab2lZ8MWeGvvx4Zr0mPpg3IhWFtvBFIiVtV9wXpvEivu9DGqBJNKdkQFXOtpKPPczb3-shNOX6xWqL25HUAn3Wufc3o$>

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
