### PR TITLE
Workshops 4841 & 11092 for OCW

### PR DESCRIPTION
**Pull request by jwchan0319**
Added OCW-freetier and OCW-livelabs directories and manifests

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues with your PR:
1. atp-kafka/extract/images/objectStorage-objectDetails.png should be all lower case
2. atp-kafka/images should be under a lab folder
3. manifest.json files should use the new oracle-livelabs repo, instead of the learning-library link
4. atp-objectstorage/create/images/01-02-ogg_details.png should use dashes instead of underscores
5. There seems to be repetitive lab files across different folders, please make sure you limit the repetitive files to make future updates and maintenance easier
Thanks!

**Comment by jwchan0319** [comment]
What do you mean by #3? Are you saying the links to the common Get Started and Need Help labs should point to the new repo? Is there a common folder in the goldengate directory or elsewhere that these links should point to?

From: Arabella Yao ***@***.***>
Sent: Monday, July 25, 2022 1:41 PM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Jenny Chan ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] Workshops 4841 & 11092 for OCW (PR #14)


@arabellayao requested changes on this pull request.

Hi! Please fix the following issues with your PR:

  1.  atp-kafka/extract/images/objectStorage-objectDetails.png should be all lower case
  2.  atp-kafka/images should be under a lab folder
  3.  manifest.json files should use the new oracle-livelabs repo, instead of the learning-library link
  4.  atp-objectstorage/create/images/01-02-ogg_details.png should use dashes instead of underscores
  5.  There seems to be repetitive lab files across different folders, please make sure you limit the repetitive files to make future updates and maintenance easier
Thanks!

**Comment by jwchan0319** [comment]
Nevermind, I found it!

From: Jenny Chan
Sent: Monday, July 25, 2022 3:22 PM
To: oracle-livelabs/goldengate ***@***.***>; oracle-livelabs/goldengate ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [External] : Re: [oracle-livelabs/goldengate] Workshops 4841 & 11092 for OCW (PR #14)

What do you mean by #3? Are you saying the links to the common Get Started and Need Help labs should point to the new repo? Is there a common folder in the goldengate directory or elsewhere that these links should point to?

From: Arabella Yao ***@***.******@***.***>>
Sent: Monday, July 25, 2022 1:41 PM
To: oracle-livelabs/goldengate ***@***.******@***.***>>
Cc: Jenny Chan ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External] : Re: [oracle-livelabs/goldengate] Workshops 4841 & 11092 for OCW (PR #14)


@arabellayao requested changes on this pull request.

Hi! Please fix the following issues with your PR:

  1.  atp-kafka/extract/images/objectStorage-objectDetails.png should be all lower case
  2.  atp-kafka/images should be under a lab folder
  3.  manifest.json files should use the new oracle-livelabs repo, instead of the learning-library link
  4.  atp-objectstorage/create/images/01-02-ogg_details.png should use dashes instead of underscores
  5.  There seems to be repetitive lab files across different folders, please make sure you limit the repetitive files to make future updates and maintenance easier
Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links or the object storage links. Refer to these files for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy. Thanks!

**Comment by jwchan0319** [comment]
@arabellayao I am in the process of consolidating files into a ggs-common folder. I'd like to merge the ggs-common folder to test the links to the images in one of my labs before making updates to the rest.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
