### PR TITLE
Updates to WMS 4861 and 2920

### PR DESCRIPTION
**Pull request by jwchan0319**
# WMS ID: 4861

Changes include:
- Updates to instructions to reflect recent changes in environment set up 
- Implement and update building blocks for reuseability

# WMS ID: 2920

Changes include:
- Updates to Monitor lab to reflect changes in building blocks

### CODE REVIEW

**Review by ramonamagadan18 — COMMENTED** [review]
Hi @jwchan0319, it looks like you have updated more than two workshops, can you give us the WMS ID for the workshop you updated the "ogg-to-ggs" folder?

**Comment by jwchan0319** [comment]
The other is 4841

[Oracle]<http://www.oracle.com/>
Jenny Chan, Consulting User Assistance Developer

Oracle Database
New York
From: Ramona Magadan ***@***.***>
Sent: Thursday, April 4, 2024 6:56 AM
To: oracle-livelabs/goldengate ***@***.***>
Cc: Jenny Chan ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/goldengate] Updates to WMS 4861 and 2920 (PR #159)


@ramonamagadan18 commented on this pull request.

Hi @jwchan0319<https://urldefense.com/v3/__https:/github.com/jwchan0319__;!!ACWV5N9M2RV99hQ!KuXrgAp5tOQ1PH7kUrt5O2jpXwBp7F6gGXfFPY-BbLetlSwTor45wv9beVZesUVUBwxWlMg1kXoSRgM0DfMY4xS0tRmiezfp$>, it looks like you have updated more than two workshops, can you give us the WMS ID for the workshop you updated the "ogg-to-ggs" folder?

**Review by ramonamagadan18 — APPROVED** [review]
Hi @jwchan0319, it looks like you have updated more than two workshops, can you give us the WMS ID for the workshop you updated the "ogg-to-ggs" folder?

**Comment by jwchan0319** [comment]
The other is 4841

**Review by ramonamagadan18 — APPROVED** [review]

**Review by klazarz — APPROVED** [review]

**Pull request merged**
